"""Generate the ten-node HTCondor DAG for the dissociation study."""

from __future__ import annotations

import argparse
import os
from dataclasses import dataclass

from _bootstrap import bootstrap, repo_path

bootstrap()

from run_activation_behavior_dissociation_manifest import STAGES, build_pair  # noqa: E402
from run_confirmatory_manifest import apply_storage_overrides  # noqa: E402
from slgeo.io import load_yaml  # noqa: E402


@dataclass
class Task:
    task_id: str
    pair_index: int
    seed: int
    stage: str
    command_index: int
    gpus: int
    cpus: int
    memory_mb: int
    min_gpu_memory_mb: int
    parents: tuple[str, ...]


def task_id(seed: int, stage: str, index: int) -> str:
    return f"abd_seed{seed}_{stage}_{index:02d}"


def build_tasks(manifest: dict) -> list[Task]:
    pairs = [build_pair(manifest, item, index) for index, item in enumerate(manifest["replicates"])]
    resources = manifest["hpc"]["resources"]
    tasks = []
    compare_ids = []
    for pair_index, pair in enumerate(pairs):
        run_ids = []
        for index, _ in enumerate(pair["stages"]["behavior_runs"]):
            resource = resources["evaluation"]
            ident = task_id(pair["seed"], "behavior_runs", index)
            run_ids.append(ident)
            tasks.append(Task(ident, pair_index, pair["seed"], "behavior_runs", index, 1, int(resource["cpus"]), int(resource["memory_mb"]), int(resource["min_gpu_memory_mb"]), ()))
        resource = resources["comparison"]
        ident = task_id(pair["seed"], "behavior_compare", 0)
        compare_ids.append(ident)
        tasks.append(Task(ident, pair_index, pair["seed"], "behavior_compare", 0, 0, int(resource["cpus"]), int(resource["memory_mb"]), 0, tuple(run_ids)))
    resource = resources["comparison"]
    tasks.append(Task(task_id(1, "aggregate", 0), 0, 1, "aggregate", 0, 0, int(resource["cpus"]), int(resource["memory_mb"]), 0, tuple(compare_ids)))
    return tasks


def validate(tasks: list[Task]) -> None:
    if len(tasks) != 10 or len({task.task_id for task in tasks}) != 10:
        raise RuntimeError("Dissociation DAG must contain ten unique tasks")
    if sum(task.gpus for task in tasks) != 6:
        raise RuntimeError("Dissociation DAG must contain six GPU tasks")
    pending = {task.task_id: set(task.parents) for task in tasks}
    while pending:
        ready = {node for node, parents in pending.items() if not parents}
        if not ready:
            raise RuntimeError("Dissociation DAG contains a cycle")
        pending = {node: parents - ready for node, parents in pending.items() if node not in ready}


def _quote(value: str) -> str:
    return value.replace("\\", "/").replace('"', '\\"')


def render(tasks: list[Task], manifest_path: str, manifest: dict, repo_root: str, shared_root: str, image: str) -> str:
    lines = ["# Generated by scripts/generate_activation_behavior_dissociation_dag.py", ""]
    retirement = int(manifest["hpc"]["max_job_retirement_seconds"])
    for task in tasks:
        submit = "condor/activation_behavior_dissociation_task_gpu.sub" if task.gpus else "condor/activation_behavior_dissociation_task_cpu.sub"
        lines.append(f"JOB {task.task_id} {submit}")
        values = {
            "BsvTaskId": task.task_id,
            "BsvPairIndex": str(task.pair_index),
            "BsvStage": task.stage,
            "BsvCommandIndex": str(task.command_index),
            "BsvManifestPath": manifest_path,
            "BsvRepoRoot": repo_root,
            "BsvSharedRoot": shared_root,
            "BsvDockerImage": image,
            "BsvRequestCpus": str(task.cpus),
            "BsvRequestMemoryMB": str(task.memory_mb),
            "BsvMinGpuMemoryMB": str(task.min_gpu_memory_mb),
            "BsvRetirementSeconds": str(retirement),
            "BsvGpuResourceAttempts": "4",
        }
        lines.append("VARS " + task.task_id + " " + " ".join(f'{key}=\"{_quote(value)}\"' for key, value in values.items()))
        lines.append(f"RETRY {task.task_id} 2 UNLESS-EXIT 85")
        lines.append("")
    for task in tasks:
        if task.parents:
            lines.append(f"PARENT {' '.join(task.parents)} CHILD {task.task_id}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", default="configs/validation/cat_activation_behavior_dissociation_v1.yaml")
    parser.add_argument("--output", default="condor/activation_behavior_dissociation.dag")
    parser.add_argument("--repo-root", default="$ENV(HOME)/beyond-steering-vectors")
    parser.add_argument("--shared-root", default="/scratch/compuling/$ENV(USER)/beyond-steering-vectors")
    parser.add_argument("--container-image", default=os.getenv("CONDOR_CONTAINER_IMAGE", "pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime"))
    args = parser.parse_args()
    manifest = apply_storage_overrides(load_yaml(repo_path(args.manifest)))
    tasks = build_tasks(manifest)
    validate(tasks)
    repo_path(args.output).write_text(
        render(tasks, args.manifest, manifest, args.repo_root, args.shared_root, args.container_image),
        encoding="utf-8",
        newline="\n",
    )
    print(f"Generated {len(tasks)} tasks ({sum(task.gpus for task in tasks)} GPU) at {args.output}")


if __name__ == "__main__":
    main()
