"""Generate the Phenotype Anchor v1 HTCondor DAGs (standard library only; runs on the submit host).

``--technical-validation``: TV-P1 (CPU validation, two GPU validations on disjoint host groups, projection).
``--plan``: scientific DAG of one stage's plan (``plan.json``, ``plan_p2.json`` or ``plan_p1-seeds45.json``):
``pin-adapters --stage`` of that stage (CPU, before any forward), then one GPU node per shard of the plan. There is no
analysis node: scientific outputs are sealed until the unseal decision.

Every node pins the execution identity (commit, digest-pinned image, NVIDIA driver) in its submit variables and
carries its budget category and run tag as job attributes. Every node has a PRE script (the budget gate); a PRE
refusal (exit 87, BUDGET_PAUSE) aborts the DAG. RETRY allows at most two further attempts and never retries exit 86.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from _bootstrap import bootstrap, repo_path

bootstrap()

from dag_notifications import append_final_notification
from generate_cts_stage0_dag import BUDGET_STOP_EXIT as BUDGET_PAUSE_EXIT
from generate_cts_stage0_dag import FINAL_EXIT, HOST_GROUP_A, HOST_GROUP_B, IMAGE, RETRIES, _quote
from slgeo.phenotype import stages  # standard library only

GPU_SUB = "condor/phenotype_task_gpu.sub"
CPU_SUB = "condor/phenotype_task_cpu.sub"
STUDY = "Phenotype Anchor v1"
RESOURCES = {
    "data-entropy": (2, 16384),
    "pin-adapters": (2, 8192),
    "plan": (2, 8192),
    "run": (4, 32768),
    "tv-cpu": (4, 16384),
    "tv": (4, 32768),
    "tv-project": (2, 16384),
}
TV_NODE_ESTIMATE_A100_H = 1.0
TV_GPU_NODES = 2
SHARD_PATTERN = r"[A-Za-z0-9_.\-]+"
DRIVER_PATTERN = r"[0-9]+\.[0-9]+(\.[0-9]+)?"


def node_name(shard_id: str) -> str:
    if not re.fullmatch(SHARD_PATTERN, shard_id):
        raise ValueError(f"Unsafe shard id {shard_id!r}")
    return "shard_" + shard_id.replace(".", "_")


def node(name: str, gpu: bool, command: str, target: str, *, commit: str, repo_root: str, shared_root: str,
         category: str, run_tag: str, driver: str, pre: list[str], machine: str = "True") -> list[str]:
    if "@sha256:" not in IMAGE:
        raise ValueError("Container image must be digest-pinned")
    resources = RESOURCES[command]
    values = {
        "BsvTaskId": name, "BsvCommand": command, "BsvTarget": target, "BsvRepoRoot": repo_root,
        "BsvSharedRoot": shared_root, "BsvDockerImage": IMAGE, "BsvRequestCpus": str(resources[0]),
        "BsvRequestMemoryMB": str(resources[1]), "BsvExecutionGitCommit": commit, "BsvMachineRequirement": machine,
        "BsvRunTag": run_tag, "BsvBudgetCategory": category, "BsvNvidiaDriver": driver,
    }
    return [
        f"JOB {name} {GPU_SUB if gpu else CPU_SUB}",
        f"VARS {name} " + " ".join(f'{key}="{_quote(value)}"' for key, value in values.items()),
        f"SCRIPT PRE {name} " + " ".join(pre),
        f"RETRY {name} {RETRIES} UNLESS-EXIT {FINAL_EXIT}",
        f"ABORT-DAG-ON {name} {BUDGET_PAUSE_EXIT} RETURN 1",
        "",
    ]


def _pre(repo_root: str, category: str, run_tag: str, name: str, out_root: str, *, cap: float = 0.0, cap_file: str = "",
         plan: str | None = None, tv_remaining: float = 0.0, accounting_root: str | None = None) -> list[str]:
    command = ["/usr/bin/env", "python3", f"{repo_root}/scripts/phenotype_budget.py", "pre", "--category", category,
               "--run-tag", run_tag, "--node", name, "--out-root", out_root]
    command += ["--cap-file", cap_file] if cap_file else ["--cap", f"{cap:g}"]
    if plan:
        command += ["--plan", plan]
    if tv_remaining:
        command += ["--tv-remaining-a100-h", f"{tv_remaining:g}"]
    if accounting_root:
        command += ["--accounting-root", accounting_root]
    return command


def technical_validation_dag(commit: str, repo_root: str, shared_root: str, run_tag: str, tv_root: str, tv_cap: float,
                             accounting_root: str, driver: str) -> str:
    lines = ["# Generated by scripts/generate_phenotype_dag.py --technical-validation (TV-P1)",
             f"# NVIDIA driver pin: {driver}", ""]
    common = {"commit": commit, "repo_root": repo_root, "shared_root": shared_root, "category": "TV", "run_tag": run_tag,
              "driver": driver}
    remaining = TV_GPU_NODES * TV_NODE_ESTIMATE_A100_H

    def pre(name):
        return _pre(repo_root, "TV", run_tag, name, tv_root, cap=tv_cap, tv_remaining=remaining if name != "tv_project" else 0.0,
                    accounting_root=accounting_root)

    lines += node("tv_cpu", False, "tv-cpu", "none", pre=pre("tv_cpu"), **common)
    for name, target, group in (("tv_gpu_a", "gpu_a", HOST_GROUP_A), ("tv_gpu_b", "gpu_b", HOST_GROUP_B)):
        lines += node(name, True, "tv", target, machine=group, pre=pre(name), **common)
    lines += node("tv_project", False, "tv-project", "none", pre=pre("tv_project"), **common)
    lines.append("PARENT tv_cpu CHILD tv_gpu_a tv_gpu_b")
    lines.append("PARENT tv_gpu_a tv_gpu_b CHILD tv_project")
    return "\n".join(lines) + "\n"


def plan_dag(plan: dict, plan_path: str, commit: str, repo_root: str, shared_root: str, run_tag: str, out_root: str,
             cap_file: str, driver: str) -> str:
    stage = plan.get("stage")
    if stage not in stages.STAGES:
        raise ValueError(f"The plan names no known stage ({stage!r})")
    lines = [f"# Generated by scripts/generate_phenotype_dag.py --plan (scientific, stage {stage}; outputs sealed, "
             "no analysis node)", f"# NVIDIA driver pin: {driver}", ""]
    common = {"commit": commit, "repo_root": repo_root, "shared_root": shared_root, "category": "SCI", "run_tag": run_tag,
              "driver": driver}

    def pre(name):
        return _pre(repo_root, "SCI", run_tag, name, out_root, cap_file=cap_file, plan=plan_path)

    lines += node("pin_adapters", False, "pin-adapters", stage, pre=pre("pin_adapters"), **common)
    names: list[str] = []
    for shard in plan["shards"]:
        name = node_name(shard["shard_id"])
        if name in names:
            raise ValueError(f"Duplicate node name {name}")
        lines += node(name, True, "run", shard["shard_id"], pre=pre(name), **common)
        names.append(name)
    if not names:
        raise ValueError("The plan has no shards")
    lines.append(f"PARENT pin_adapters CHILD {' '.join(names)}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--technical-validation", action="store_true")
    mode.add_argument("--plan")
    parser.add_argument("--output", required=True)
    parser.add_argument("--execution-git-commit", required=True)
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--shared-root", required=True)
    parser.add_argument("--run-tag", required=True)
    parser.add_argument("--out-root", required=True)
    parser.add_argument("--nvidia-driver", required=True)
    parser.add_argument("--cap", type=float, default=0.0, help="TV cap (A100-h)")
    parser.add_argument("--cap-file", default="", help="scientific cap record (accounting/cap.json)")
    parser.add_argument("--accounting-root", default="")
    parser.add_argument("--ntfy-topic", default="")
    parser.add_argument("--start-epoch", type=int, default=0)
    args = parser.parse_args()
    if not re.fullmatch(r"[0-9a-f]{40}", args.execution_git_commit):
        raise ValueError("Execution commit must be a full SHA-1")
    if not re.fullmatch(r"[A-Za-z0-9_\-]+", args.run_tag):
        raise ValueError("Unsafe run tag")
    if not re.fullmatch(DRIVER_PATTERN, args.nvidia_driver):
        raise ValueError("The NVIDIA driver must be a pinned version (no placeholder)")
    if args.technical_validation:
        if not args.accounting_root or args.cap <= 0:
            raise ValueError("--accounting-root and a positive --cap are required for the technical-validation DAG")
        dag = technical_validation_dag(args.execution_git_commit, args.repo_root, args.shared_root, args.run_tag, args.out_root,
                                       args.cap, args.accounting_root, args.nvidia_driver)
    else:
        if not args.cap_file:
            raise ValueError("--cap-file is required for the scientific DAG")
        plan = json.loads(Path(args.plan).read_text(encoding="utf-8"))
        dag = plan_dag(plan, args.plan, args.execution_git_commit, args.repo_root, args.shared_root, args.run_tag, args.out_root,
                       args.cap_file, args.nvidia_driver)
    dag = append_final_notification(
        dag, study=STUDY, git_commit=args.execution_git_commit, result_path="n/a", ntfy_topic=args.ntfy_topic,
        start_epoch=args.start_epoch, container_image=IMAGE, repo_root=args.repo_root, node_name="phenotype_notify",
        budget_stop_marker=f"{args.out_root}/orchestration/BUDGET_PAUSE.json",
    )
    output = repo_path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(dag, encoding="utf-8", newline="\n")
    print(f"DAG written to {output}")


if __name__ == "__main__":
    main()
