"""Generate the three-node DAG for Final-State Directional Decomposition v1."""

from __future__ import annotations

import argparse
import os
from dataclasses import dataclass

from _bootstrap import bootstrap, repo_path

bootstrap()

from dag_notifications import append_final_notification  # noqa: E402
from run_confirmatory_manifest import apply_storage_overrides  # noqa: E402
from run_final_state_directional_decomposition_manifest import build_pair  # noqa: E402
from slgeo.io import load_yaml  # noqa: E402


@dataclass(frozen=True)
class Task:
    task_id: str
    stage: str
    command_index: int
    gpus: int
    cpus: int
    memory_mb: int
    min_gpu_memory_mb: int
    parents: tuple[str, ...]


def build_tasks(manifest: dict) -> list[Task]:
    pair = build_pair(manifest)
    resources = manifest["hpc"]["resources"]
    extraction = resources["extraction"]
    state_tasks = [
        Task(
            f"fsd_state_{index:02d}", "state_runs", index, 1,
            int(extraction["cpus"]), int(extraction["memory_mb"]),
            int(extraction["min_gpu_memory_mb"]), (),
        )
        for index, _ in enumerate(pair["stages"]["state_runs"])
    ]
    aggregation = resources["aggregation"]
    return state_tasks + [Task(
        "fsd_aggregate_00", "aggregate", 0, 0,
        int(aggregation["cpus"]), int(aggregation["memory_mb"]), 0,
        tuple(task.task_id for task in state_tasks),
    )]


def validate(tasks: list[Task]) -> None:
    if len(tasks) != 3 or len({task.task_id for task in tasks}) != 3:
        raise RuntimeError("Directional decomposition DAG must contain three unique tasks")
    if sum(task.gpus for task in tasks) != 2:
        raise RuntimeError("Directional decomposition DAG must contain two GPU tasks")
    pending = {task.task_id: set(task.parents) for task in tasks}
    while pending:
        ready = {name for name, parents in pending.items() if not parents}
        if not ready:
            raise RuntimeError("Directional decomposition DAG contains a cycle")
        pending = {name: parents - ready for name, parents in pending.items() if name not in ready}


def _quote(value: str) -> str:
    return value.replace("\\", "/").replace('"', '\\"')


def render(
    tasks: list[Task], manifest_path: str, manifest: dict, repo_root: str,
    shared_root: str, image: str, *, ntfy_topic: str = "",
    start_epoch: int = 0, execution_git_commit: str = "UNFROZEN",
) -> str:
    lines = ["# Generated by scripts/generate_final_state_directional_decomposition_dag.py", ""]
    retirement = int(manifest["hpc"]["max_job_retirement_seconds"])
    for task in tasks:
        submit = "condor/final_state_directional_decomposition_task_gpu.sub" if task.gpus else "condor/final_state_directional_decomposition_task_cpu.sub"
        lines.append(f"JOB {task.task_id} {submit}")
        values = {
            "BsvTaskId": task.task_id,
            "BsvPairIndex": "0",
            "BsvStage": task.stage,
            "BsvCommandIndex": str(task.command_index),
            "BsvManifestPath": manifest_path,
            "BsvRepoRoot": repo_root,
            "BsvSharedRoot": shared_root,
            "BsvDockerImage": image,
            "BsvRequestCpus": str(task.cpus),
            "BsvRequestMemoryMB": str(task.memory_mb),
            "BsvMinGpuMemoryMB": str(task.min_gpu_memory_mb),
            "BsvRetirementSeconds": str(retirement),
            "BsvGpuResourceAttempts": "4",
            "BsvExecutionGitCommit": execution_git_commit,
        }
        lines.append("VARS " + task.task_id + " " + " ".join(f'{key}=\"{_quote(value)}\"' for key, value in values.items()))
        lines.append(f"RETRY {task.task_id} 2 UNLESS-EXIT 85")
        lines.append("")
    for task in tasks:
        if task.parents:
            lines.append(f"PARENT {' '.join(task.parents)} CHILD {task.task_id}")
    return append_final_notification(
        "\n".join(lines) + "\n",
        study="Final-State Directional Causal Decomposition v1",
        git_commit=execution_git_commit,
        result_path=str(manifest["output_root"]),
        ntfy_topic=ntfy_topic,
        start_epoch=start_epoch,
        repo_root=repo_root,
        node_name="fsd_notify",
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", default="configs/validation/cat_final_state_directional_causal_decomposition_v1.yaml")
    parser.add_argument("--output", default="condor/final_state_directional_decomposition.dag")
    parser.add_argument("--repo-root", default="$ENV(HOME)/beyond-steering-vectors")
    parser.add_argument("--shared-root", default="/scratch/compuling/$ENV(USER)/beyond-steering-vectors")
    parser.add_argument("--container-image", default=os.getenv("CONDOR_CONTAINER_IMAGE", "pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime"))
    parser.add_argument("--ntfy-topic", default="")
    parser.add_argument("--start-epoch", type=int, default=0)
    parser.add_argument("--execution-git-commit", default="UNFROZEN")
    args = parser.parse_args()
    manifest = apply_storage_overrides(load_yaml(repo_path(args.manifest)))
    tasks = build_tasks(manifest)
    validate(tasks)
    repo_path(args.output).write_text(
        render(
            tasks, args.manifest, manifest, args.repo_root, args.shared_root,
            args.container_image, ntfy_topic=args.ntfy_topic,
            start_epoch=args.start_epoch,
            execution_git_commit=args.execution_git_commit,
        ),
        encoding="utf-8", newline="\n",
    )
    print(f"Generated {len(tasks)} tasks ({sum(task.gpus for task in tasks)} GPU) at {args.output}")


if __name__ == "__main__":
    main()
