"""Generate the CTS Stage-0 HTCondor DAGs (standard library only; runs on the submit host).

``--technical-validation``: CPU validation node plus two GPU validation nodes on disjoint host groups.
``--plan``: one node per shard of the scientific plan (``plan.json`` from the plan job), with dependencies.
Every node pins the execution identity in its submit file; RETRY never retries exit 86 (identity/integrity).
The FINAL notification carries only the pipeline status (no result path, no numbers).
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from _bootstrap import repo_path

from dag_notifications import append_final_notification

IMAGE = "pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime@sha256:c8268a92a69bd500f8be0e665b2630ee006dadaf7bfbc24249141b15ff622755"
GPU_SUB = "condor/cts_stage0_task_gpu.sub"
CPU_SUB = "condor/cts_stage0_task_cpu.sub"
STUDY = "CTS Stage 0"
# Disjoint host groups of the pinned A100-PCIE-40GB / 570.211.01 pool (repeat-determinism on two machines).
HOST_GROUP_A = 'regexp("^f", Machine)'
HOST_GROUP_B = 'regexp("^g", Machine)'
RESOURCES = {
    "plan": (2, 8192),
    "preflight": (4, 16384),
    "extract": (4, 32768),
    "directions": (4, 32768),
    "baseline": (4, 32768),
    "score": (4, 32768),
    "score_persona": (4, 32768),
    "sample": (4, 32768),
    "integrity": (4, 32768),
    "analysis": (4, 49152),
    "techval": (4, 32768),
    "techval-cpu": (4, 16384),
}
SIGTERM_RETRIES = 5


def _quote(value: str) -> str:
    return value.replace("\\", "/").replace('"', '\\"')


def node(name: str, gpu: bool, command: str, target: str, resources: tuple[int, int], commit: str, repo_root: str,
         shared_root: str, machine: str = "True") -> list[str]:
    if "@sha256:" not in IMAGE:
        raise ValueError("Container image must be digest-pinned")
    values = {
        "BsvTaskId": name, "BsvCommand": command, "BsvTarget": target, "BsvRepoRoot": repo_root,
        "BsvSharedRoot": shared_root, "BsvDockerImage": IMAGE, "BsvRequestCpus": str(resources[0]),
        "BsvRequestMemoryMB": str(resources[1]), "BsvExecutionGitCommit": commit, "BsvMachineRequirement": machine,
    }
    return [
        f"JOB {name} {GPU_SUB if gpu else CPU_SUB}",
        f"VARS {name} " + " ".join(f'{key}="{_quote(value)}"' for key, value in values.items()),
        f"RETRY {name} {SIGTERM_RETRIES} UNLESS-EXIT 86",
        "",
    ]


def technical_validation_dag(commit: str, repo_root: str, shared_root: str) -> str:
    lines = ["# Generated by scripts/generate_cts_stage0_dag.py --technical-validation", ""]
    lines += node("tv_cpu", False, "techval-cpu", "none", RESOURCES["techval-cpu"], commit, repo_root, shared_root)
    lines += node("tv_gpu_a", True, "techval", "gpu_a", RESOURCES["techval"], commit, repo_root, shared_root, HOST_GROUP_A)
    lines += node("tv_gpu_b", True, "techval", "gpu_b", RESOURCES["techval"], commit, repo_root, shared_root, HOST_GROUP_B)
    lines.append("PARENT tv_cpu CHILD tv_gpu_a tv_gpu_b")
    return "\n".join(lines) + "\n"


def plan_dag(plan: dict, commit: str, repo_root: str, shared_root: str) -> str:
    lines = ["# Generated by scripts/generate_cts_stage0_dag.py --plan", ""]
    stages: dict[str, list[str]] = {}
    for shard in plan["shards"]:
        shard_id = shard["shard_id"]
        if not re.fullmatch(r"[A-Za-z0-9_\-]+", shard_id):
            raise ValueError(f"Unsafe shard id {shard_id!r}")
        stage = shard["stage"]
        machine = "True"
        if shard_id == "baseline_rep1":
            machine = HOST_GROUP_A
        elif shard_id == "baseline_rep2":
            machine = HOST_GROUP_B
        lines += node(shard_id, bool(shard["gpu"]), "run", shard_id, RESOURCES[stage], commit, repo_root, shared_root, machine)
        stages.setdefault(stage, []).append(shard_id)
    order = [
        (["preflight"], stages.get("extract", [])),
        (stages.get("extract", []), ["directions"]),
        (["directions"], stages.get("baseline", []) + stages.get("sample", [])),
        (["baseline_rep1"], stages.get("score", []) + stages.get("score_persona", [])),
        (stages.get("baseline", []) + stages.get("score", []) + stages.get("score_persona", []) + stages.get("sample", []), ["integrity"]),
        (["integrity"], ["analysis"]),
    ]
    for parents, children in order:
        if parents and children:
            lines.append(f"PARENT {' '.join(parents)} CHILD {' '.join(children)}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--technical-validation", action="store_true")
    mode.add_argument("--plan")
    parser.add_argument("--output", required=True)
    parser.add_argument("--execution-git-commit", required=True)
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--shared-root", required=True)
    parser.add_argument("--ntfy-topic", default="")
    parser.add_argument("--start-epoch", type=int, default=0)
    args = parser.parse_args()
    if not re.fullmatch(r"[0-9a-f]{40}", args.execution_git_commit):
        raise ValueError("Execution commit must be a full SHA-1")
    if args.technical_validation:
        dag = technical_validation_dag(args.execution_git_commit, args.repo_root, args.shared_root)
    else:
        dag = plan_dag(json.loads(Path(args.plan).read_text(encoding="utf-8")), args.execution_git_commit, args.repo_root, args.shared_root)
    dag = append_final_notification(
        dag, study=STUDY, git_commit=args.execution_git_commit, result_path="n/a", ntfy_topic=args.ntfy_topic,
        start_epoch=args.start_epoch, container_image=IMAGE, repo_root=args.repo_root, node_name="cts_notify",
    )
    output = repo_path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(dag, encoding="utf-8", newline="\n")
    print(f"DAG written to {output}")


if __name__ == "__main__":
    main()
