"""Generate the CTS Stage-0 v2 HTCondor DAGs (standard library only; runs on the submit host).

``--technical-validation``: TV-v2 (CPU validation, two GPU validations on disjoint host groups, projection).
``--plan``: one node per shard of the scientific plan (``plan.json`` from the plan job), with dependencies.

Every node pins the execution identity in its submit file and carries its budget category and run tag as job
attributes (E4 accounting). Every node has a PRE script (the budget gate); a PRE refusal (exit 87) aborts the
DAG. RETRY allows at most two further attempts and never retries exit 86 (final failures, E2).
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from _bootstrap import repo_path

from dag_notifications import append_final_notification

IMAGE = "pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime@sha256:c8268a92a69bd500f8be0e665b2630ee006dadaf7bfbc24249141b15ff622755"
GPU_SUB = "condor/cts_stage0_task_gpu.sub"
CPU_SUB = "condor/cts_stage0_task_cpu.sub"
STUDY = "CTS Stage 0 v2"
HOST_GROUP_A = 'regexp("^f", Machine)'
HOST_GROUP_B = 'regexp("^g", Machine)'
RESOURCES = {
    "plan": (2, 8192),
    "preflight": (4, 16384),
    "extract": (4, 32768),
    "directions": (4, 32768),
    "baseline": (4, 32768),
    "score": (4, 32768),
    "rescore": (4, 32768),
    "fragility": (4, 49152),
    "integrity": (4, 32768),
    "analysis": (4, 49152),
    "techval": (4, 32768),
    "techval-cpu": (4, 16384),
    "tv-project": (2, 16384),
    "techval-dry": (4, 32768),
}
RETRIES = 2
FINAL_EXIT = 86
BUDGET_STOP_EXIT = 87
TV_NODE_ESTIMATE_A100_H = 1.0
TV_GPU_NODES = 3


def _quote(value: str) -> str:
    return value.replace("\\", "/").replace('"', '\\"')


def node(name: str, gpu: bool, command: str, target: str, resources: tuple[int, int], *, commit: str, repo_root: str,
         shared_root: str, category: str, run_tag: str, pre: list[str], machine: str = "True") -> list[str]:
    if "@sha256:" not in IMAGE:
        raise ValueError("Container image must be digest-pinned")
    values = {
        "BsvTaskId": name, "BsvCommand": command, "BsvTarget": target, "BsvRepoRoot": repo_root,
        "BsvSharedRoot": shared_root, "BsvDockerImage": IMAGE, "BsvRequestCpus": str(resources[0]),
        "BsvRequestMemoryMB": str(resources[1]), "BsvExecutionGitCommit": commit, "BsvMachineRequirement": machine,
        "BsvRunTag": run_tag, "BsvBudgetCategory": category,
    }
    return [
        f"JOB {name} {GPU_SUB if gpu else CPU_SUB}",
        f"VARS {name} " + " ".join(f'{key}="{_quote(value)}"' for key, value in values.items()),
        f"SCRIPT PRE {name} " + " ".join(pre),
        f"RETRY {name} {RETRIES} UNLESS-EXIT {FINAL_EXIT}",
        f"ABORT-DAG-ON {name} {BUDGET_STOP_EXIT} RETURN 1",
        "",
    ]


def _pre(repo_root: str, category: str, run_tag: str, name: str, out_root: str, cap: float, *, plan: str | None = None,
         tv_remaining: float = 0.0, accounting_root: str | None = None) -> list[str]:
    command = ["/usr/bin/env", "python3", f"{repo_root}/scripts/cts_stage0_budget.py", "pre", "--category", category,
               "--run-tag", run_tag, "--node", name, "--out-root", out_root, "--cap", f"{cap:g}"]
    if plan:
        command += ["--plan", plan]
    if tv_remaining:
        command += ["--tv-remaining-a100-h", f"{tv_remaining:g}"]
    if accounting_root:
        command += ["--accounting-root", accounting_root]
    return command


def technical_validation_dag(commit: str, repo_root: str, shared_root: str, run_tag: str, tv_root: str, tv_cap: float,
                             accounting_root: str) -> str:
    lines = ["# Generated by scripts/generate_cts_stage0_dag.py --technical-validation (TV-v2)", ""]
    common = {"commit": commit, "repo_root": repo_root, "shared_root": shared_root, "category": "TV", "run_tag": run_tag}
    remaining = TV_GPU_NODES * TV_NODE_ESTIMATE_A100_H

    def pre(name):
        return _pre(repo_root, "TV", run_tag, name, tv_root, tv_cap, tv_remaining=remaining if name != "tv_project" else 0.0,
                    accounting_root=accounting_root)

    lines += node("tv_cpu", False, "techval-cpu", "none", RESOURCES["techval-cpu"], pre=pre("tv_cpu"), **common)
    for name, target, group in (("tv_gpu_a", "gpu_a", HOST_GROUP_A), ("tv_gpu_b", "gpu_b", HOST_GROUP_B)):
        lines += node(name, True, "techval", target, RESOURCES["techval"], machine=group, pre=pre(name), **common)
    lines += node("tv_dry", True, "techval-dry", "none", RESOURCES["techval-dry"], pre=pre("tv_dry"), **common)
    lines += node("tv_project", False, "tv-project", "none", RESOURCES["tv-project"], pre=pre("tv_project"), **common)
    lines.append("PARENT tv_cpu CHILD tv_gpu_a tv_gpu_b tv_dry")
    lines.append("PARENT tv_gpu_a tv_gpu_b tv_dry CHILD tv_project")
    return "\n".join(lines) + "\n"


def plan_dag(plan: dict, plan_path: str, commit: str, repo_root: str, shared_root: str, run_tag: str, out_root: str, cap: float) -> str:
    lines = ["# Generated by scripts/generate_cts_stage0_dag.py --plan (scientific, v2)", ""]
    stages: dict[str, list[str]] = {}
    common = {"commit": commit, "repo_root": repo_root, "shared_root": shared_root, "category": "SCI", "run_tag": run_tag}
    for shard in plan["shards"]:
        shard_id = shard["shard_id"]
        if not re.fullmatch(r"[A-Za-z0-9_\-]+", shard_id):
            raise ValueError(f"Unsafe shard id {shard_id!r}")
        stage = shard["stage"]
        machine = {"baseline_rep1": HOST_GROUP_A, "baseline_rep2": HOST_GROUP_B}.get(shard_id, "True")
        lines += node(shard_id, bool(shard["gpu"]), "run", shard_id, RESOURCES[stage], machine=machine,
                      pre=_pre(repo_root, "SCI", run_tag, shard_id, out_root, cap, plan=plan_path), **common)
        stages.setdefault(stage, []).append(shard_id)
    order = [
        (["preflight"], stages.get("extract", [])),
        (stages.get("extract", []), ["directions"]),
        (["directions"], stages.get("baseline", [])),
        (["baseline_rep1"], stages.get("score", []) + stages.get("rescore", [])),
        (stages.get("baseline", []) + stages.get("score", []) + stages.get("rescore", []), ["fragility"]),
        (["fragility"], ["integrity"]),
        (["integrity"], ["analysis"]),
    ]
    for parents, children in order:
        if parents and children:
            lines.append(f"PARENT {' '.join(parents)} CHILD {' '.join(children)}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--technical-validation", action="store_true")
    mode.add_argument("--plan")
    parser.add_argument("--output", required=True)
    parser.add_argument("--execution-git-commit", required=True)
    parser.add_argument("--repo-root", required=True)
    parser.add_argument("--shared-root", required=True)
    parser.add_argument("--run-tag", required=True)
    parser.add_argument("--out-root", required=True)
    parser.add_argument("--cap", required=True, type=float)
    parser.add_argument("--accounting-root", default="")
    parser.add_argument("--ntfy-topic", default="")
    parser.add_argument("--start-epoch", type=int, default=0)
    args = parser.parse_args()
    if not re.fullmatch(r"[0-9a-f]{40}", args.execution_git_commit):
        raise ValueError("Execution commit must be a full SHA-1")
    if not re.fullmatch(r"[A-Za-z0-9_\-]+", args.run_tag):
        raise ValueError("Unsafe run tag")
    if args.technical_validation:
        if not args.accounting_root:
            raise ValueError("--accounting-root is required for the technical-validation DAG")
        dag = technical_validation_dag(args.execution_git_commit, args.repo_root, args.shared_root, args.run_tag, args.out_root, args.cap,
                                       args.accounting_root)
    else:
        plan = json.loads(Path(args.plan).read_text(encoding="utf-8"))
        dag = plan_dag(plan, args.plan, args.execution_git_commit, args.repo_root, args.shared_root, args.run_tag, args.out_root, args.cap)
    dag = append_final_notification(
        dag, study=STUDY, git_commit=args.execution_git_commit, result_path="n/a", ntfy_topic=args.ntfy_topic,
        start_epoch=args.start_epoch, container_image=IMAGE, repo_root=args.repo_root, node_name="cts_notify",
        budget_stop_marker=f"{args.out_root}/orchestration/BUDGET_STOP.json",
    )
    output = repo_path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(dag, encoding="utf-8", newline="\n")
    print(f"DAG written to {output}")


if __name__ == "__main__":
    main()
