"""Generate the HTCondor DAG for parameter-hardening Phase 1."""

from __future__ import annotations

import argparse
import json
import os
from dataclasses import asdict, dataclass

from _bootstrap import bootstrap, repo_path

bootstrap()

from run_confirmatory_manifest import apply_storage_overrides  # noqa: E402
from run_parameter_hardening_manifest import STAGES, build_pair  # noqa: E402
from slgeo.io import load_yaml  # noqa: E402


@dataclass
class Task:
    task_id: str
    pair_index: int
    seed: int
    stage: str
    command_index: int
    command: list[str]
    gpus: int
    cpus: int
    memory_mb: int
    min_gpu_memory_mb: int
    parents: tuple[str, ...]


def task_id(seed: int, stage: str, index: int) -> str:
    return f"seed{seed}_{stage}_{index:02d}"


def _gpu(command: list[str]) -> bool:
    return command[0] in {
        "scripts/extract_steering_vectors.py", "scripts/run_lora_attribution.py",
        "scripts/run_lora_set_interventions.py", "scripts/run_lora_set_behavior.py",
    }


def build_tasks(manifest: dict) -> list[Task]:
    pairs = [build_pair(manifest, item, i) for i, item in enumerate(manifest["replicates"])]
    resources = manifest["hpc"]["resources"]
    raw: dict[str, dict] = {}
    for pair_index, pair in enumerate(pairs):
        for stage in STAGES:
            for index, command in enumerate(pair["stages"][stage]):
                ident = task_id(pair["seed"], stage, index)
                resource = resources["attribution" if _gpu(command) else "comparison"]
                if command[0] in {"scripts/extract_steering_vectors.py", "scripts/run_lora_set_behavior.py"}:
                    resource = resources["evaluation"]
                raw[ident] = {
                    "task_id": ident, "pair_index": pair_index, "seed": pair["seed"],
                    "stage": stage, "command_index": index, "command": command,
                    "gpus": int(resource.get("gpus", 0)), "cpus": int(resource["cpus"]),
                    "memory_mb": int(resource["memory_mb"]),
                    "min_gpu_memory_mb": int(resource.get("min_gpu_memory_mb", 0)),
                    "parents": [],
                }

    def parent(child: str, *parents: str) -> None:
        raw[child]["parents"].extend(item for item in parents if item in raw)

    teachers = [task_id(1, "teacher_vectors", i) for i in range(2)]
    for pair in pairs:
        seed = pair["seed"]
        module_runs = [task_id(seed, "module_runs", i) for i in range(2)]
        module_compare = task_id(seed, "module_compare", 0)
        parent(module_compare, *module_runs)
        topk = task_id(seed, "topk_prepare", 0)
        parent(topk, module_compare)
        for stage in ("activation_runs", "behavior_runs"):
            for i in range(2):
                parent(task_id(seed, stage, i), topk)
        parent(task_id(seed, "activation_compare", 0), *[task_id(seed, "activation_runs", i) for i in range(2)])
        parent(task_id(seed, "behavior_compare", 0), *[task_id(seed, "behavior_runs", i) for i in range(2)])
        for i in range(4):
            parent(task_id(seed, "robustness_runs", i), teachers[i // 2])
        for i in range(2):
            parent(task_id(seed, "robustness_compare", i), task_id(seed, "robustness_runs", 2 * i), task_id(seed, "robustness_runs", 2 * i + 1))

    parent(task_id(1, "aggregate", 0), *[task_id(seed, stage, 0) for seed in (1, 2, 3) for stage in ("activation_compare", "behavior_compare")])
    parent(task_id(1, "aggregate", 1), *[task_id(seed, "module_compare", 0) for seed in (1, 2, 3)], *[task_id(seed, "robustness_compare", i) for seed in (1, 2, 3) for i in range(2)])
    return [Task(**{**item, "parents": tuple(sorted(set(item["parents"])))}) for item in raw.values()]


def _quote(value: str) -> str:
    return value.replace("\\", "/").replace('"', '\\"')


def render(tasks: list[Task], manifest_path: str, manifest: dict, repo_root: str, shared_root: str, image: str) -> str:
    lines = ["# Generated by scripts/generate_parameter_hardening_dag.py", ""]
    retirement = int(manifest["hpc"]["max_job_retirement_seconds"])
    for task in tasks:
        submit = "condor/parameter_hardening_task_gpu.sub" if task.gpus else "condor/parameter_hardening_task_cpu.sub"
        lines.append(f"JOB {task.task_id} {submit}")
        values = {
            "BsvTaskId": task.task_id, "BsvPairIndex": str(task.pair_index),
            "BsvStage": task.stage, "BsvCommandIndex": str(task.command_index),
            "BsvManifestPath": manifest_path, "BsvRepoRoot": repo_root,
            "BsvSharedRoot": shared_root, "BsvDockerImage": image,
            "BsvRequestCpus": str(task.cpus), "BsvRequestMemoryMB": str(task.memory_mb),
            "BsvMinGpuMemoryMB": str(task.min_gpu_memory_mb),
            "BsvRetirementSeconds": str(retirement), "BsvGpuResourceAttempts": "4",
        }
        lines.append("VARS " + task.task_id + " " + " ".join(f'{key}=\"{_quote(value)}\"' for key, value in values.items()))
        lines.append(f"RETRY {task.task_id} 2 UNLESS-EXIT 85")
        lines.append("")
    for task in tasks:
        if task.parents:
            lines.append(f"PARENT {' '.join(task.parents)} CHILD {task.task_id}")
    return "\n".join(lines) + "\n"


def validate(tasks: list[Task]) -> None:
    ids = {task.task_id for task in tasks}
    if len(tasks) != 52 or len(ids) != 52:
        raise RuntimeError(f"Expected 52 unique Phase-1 tasks, got {len(tasks)} / {len(ids)}")
    pending = {task.task_id: set(task.parents) for task in tasks}
    while pending:
        ready = {node for node, parents in pending.items() if not parents}
        if not ready:
            raise RuntimeError("Phase-1 DAG contains a cycle")
        pending = {node: parents - ready for node, parents in pending.items() if node not in ready}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", default="configs/validation/cat_parameter_hardening_v1.yaml")
    parser.add_argument("--output", default="condor/parameter_hardening.dag")
    parser.add_argument("--tasks-output", help="Optional environment-specific command inventory JSON")
    parser.add_argument("--repo-root", default="$ENV(HOME)/beyond-steering-vectors")
    parser.add_argument("--shared-root", default="/scratch/compuling/$ENV(USER)/beyond-steering-vectors")
    parser.add_argument("--container-image", default=os.getenv("CONDOR_CONTAINER_IMAGE", "pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime"))
    args = parser.parse_args()
    manifest = apply_storage_overrides(load_yaml(repo_path(args.manifest)))
    tasks = build_tasks(manifest)
    validate(tasks)
    dag = render(tasks, args.manifest, manifest, args.repo_root, args.shared_root, args.container_image)
    repo_path(args.output).write_text(dag, encoding="utf-8", newline="\n")
    if args.tasks_output:
        repo_path(args.tasks_output).write_text(json.dumps({"schema_version": 1, "task_count": len(tasks), "tasks": [asdict(task) for task in tasks]}, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"task_count": len(tasks), "gpu_tasks": sum(task.gpus for task in tasks), "dag": args.output}, indent=2))


if __name__ == "__main__":
    main()
